name: CI

on: [push, pull_request]

jobs:
  build:
    name: Build

    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - name: Checkout Git repository
        uses: actions/checkout@v3
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'yarn'
      - name: Install dependencies with Yarn
        run: yarn install --immutable
      - name: Build
        run: yarn run build
      - name: Upload compiled TypeScript
        uses: actions/upload-artifact@v3
        with:
          name: dist
          path: dist
  lint:
    name: Lint

    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - name: Checkout Git repository
        uses: actions/checkout@v3
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'yarn'
      - name: Install dependencies with Yarn
        run: yarn install --immutable
      - name: Lint
        run: yarn run lint
  validate-api:
          name: Validate API

          runs-on: ubuntu-latest
          timeout-minutes: 5

          steps:
            - name: Checkout Git repository
              uses: actions/checkout@v3
            - name: Setup Node.js
              uses: actions/setup-node@v3
              with:
                node-version: '18'
                cache: 'yarn'
            - name: Install dependencies with Yarn
              run: yarn install --immutable
            - name: Build package
              run: yarn run build
            - name: Validate API
              run: yarn run validate-api
