name: CI

on: [push, pull_request]

jobs:
  build:
    name: Build

    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - name: Checkout Git repository
        uses: actions/checkout@v4
      - name: Setup Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: '1.0.0'
      - name: Install dependencies with Bun
        run: bun install --frozen-lockfile
      - name: Build
        run: bun run build
      - name: Upload compiled TypeScript
        uses: actions/upload-artifact@v4
        with:
          name: dist
          path: dist
  docs:
    name: Generate docs

    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - name: Checkout Git repository
        uses: actions/checkout@v4
      - name: Setup Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: '1.0.0'
      - name: Install dependencies with Bun
        run: bun install --frozen-lockfile
      - name: Generate docs
        run: bun run docs
      - name: Upload compiled TypeScript
        uses: actions/upload-artifact@v4
        with:
          name: docs
          path: docs
  lint:
    name: Lint

    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - name: Checkout Git repository
        uses: actions/checkout@v4
      - name: Setup Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: '1.0.0'
      - name: Install dependencies with Bun
        run: bun install --frozen-lockfile
      - name: Lint
        run: bun run lint
  test:
    name: Test

    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - name: Checkout Git repository
        uses: actions/checkout@v4
      - name: Setup Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: '1.0.0'
      - name: Install dependencies with Bun
        run: bun install --frozen-lockfile
      - name: Test
        run: bun run test:coverage
  validate-api:
    name: Validate API

    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - name: Checkout Git repository
        uses: actions/checkout@v4
      - name: Setup Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: '1.0.0'
      - name: Install dependencies with Bun
        run: bun install --frozen-lockfile
      - name: Build package
        run: bun run build
      - name: Validate API
        run: bun run validate-api
  publish:
    name: Publish

    runs-on: ubuntu-latest
    timeout-minutes: 30

    if: ${{ github.ref  == 'refs/heads/main' }}

    needs: [lint, test, validate-api]

    permissions:
      contents: write

    steps:
      - name: Checkout git repository
        uses: actions/checkout@v4
      - name: Setup Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: '1.0.0'
      - name: Install dependencies with Bun
        run: bun install --frozen-lockfile
      - name: Build package
        run: bun run build
      - name: Generate TypeScript declaration rollup
        run: bun run validate-api
      - name: Run release
        run: bun run release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
